trigger:
- MASTER

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 'Infra'
    displayName: 'Infra'
    jobs:
    - job: 'CreateVM'
      displayName: 'Create VM'
      steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'a54f3e5d-8705-4cff-98a5-329900c7248d'
          scriptType: 'pscore'
          scriptLocation: 'scriptPath'
          scriptPath: "init-environment.ps1"
          addSpnToEnvironment: true
